### ISSUE TITLE
Issue with one of the examples

### ISSUE THREAD

**Issue by AurisAudentis** [adamshaylor/cooking-with-typescript#1]
The example shown [here](https://github.com/adamshaylor/cooking-with-typescript/blob/fa56171f8eca7737953db09380dfb1d3227548c4/Contents/2-Everyday-types/Inference-in-array-methods.ts#L24) has a confusing name: 'incrementArrayMutably', because it does not mutate the arguments as 'number' is a local variable instead of an array assignment.

**Comment by melkir** [comment]
It does not mutate the value because [primitive](https://developer.mozilla.org/en-US/docs/Glossary/Primitive) values are immutable.

On the other hand, Arrays are not primitive, so we can set their properties.
```
const incrementArrayMutably = (numbers) => {
  numbers.forEach((_, index) => (numbers[index] += 1));
  return numbers;
}
```

**Comment by adamshaylor** [comment]
Good find! Thank you.
